/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/about-my-job': RouteRecordInfo<
      '/posts/about-my-job',
      '/posts/about-my-job',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/albums_creater': RouteRecordInfo<
      '/posts/albums_creater',
      '/posts/albums_creater',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Arknights_extract': RouteRecordInfo<
      '/posts/Arknights_extract',
      '/posts/Arknights_extract',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/build-env-for-rasa': RouteRecordInfo<
      '/posts/build-env-for-rasa',
      '/posts/build-env-for-rasa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/build-shadowsocks': RouteRecordInfo<
      '/posts/build-shadowsocks',
      '/posts/build-shadowsocks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cpp-libwebsockets-server-example': RouteRecordInfo<
      '/posts/cpp-libwebsockets-server-example',
      '/posts/cpp-libwebsockets-server-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cpp-opencv-mat': RouteRecordInfo<
      '/posts/cpp-opencv-mat',
      '/posts/cpp-opencv-mat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cpp-std-sort': RouteRecordInfo<
      '/posts/cpp-std-sort',
      '/posts/cpp-std-sort',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-boost': RouteRecordInfo<
      '/posts/cross-compile-boost',
      '/posts/cross-compile-boost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-fmt': RouteRecordInfo<
      '/posts/cross-compile-fmt',
      '/posts/cross-compile-fmt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-numcpp': RouteRecordInfo<
      '/posts/cross-compile-numcpp',
      '/posts/cross-compile-numcpp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-opencv': RouteRecordInfo<
      '/posts/cross-compile-opencv',
      '/posts/cross-compile-opencv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-qt5': RouteRecordInfo<
      '/posts/cross-compile-qt5',
      '/posts/cross-compile-qt5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-spdlog': RouteRecordInfo<
      '/posts/cross-compile-spdlog',
      '/posts/cross-compile-spdlog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-tutorial': RouteRecordInfo<
      '/posts/cross-compile-tutorial',
      '/posts/cross-compile-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cross-compile-x264': RouteRecordInfo<
      '/posts/cross-compile-x264',
      '/posts/cross-compile-x264',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CSharp-sort-files-with-name': RouteRecordInfo<
      '/posts/CSharp-sort-files-with-name',
      '/posts/CSharp-sort-files-with-name',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cuda-vector-allocator': RouteRecordInfo<
      '/posts/cuda-vector-allocator',
      '/posts/cuda-vector-allocator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/daily-record-1': RouteRecordInfo<
      '/posts/daily-record-1',
      '/posts/daily-record-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/daily-record-3': RouteRecordInfo<
      '/posts/daily-record-3',
      '/posts/daily-record-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/daily-record-4': RouteRecordInfo<
      '/posts/daily-record-4',
      '/posts/daily-record-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-on-wsl2': RouteRecordInfo<
      '/posts/docker-on-wsl2',
      '/posts/docker-on-wsl2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ffmpeg-rtsp-on-m2': RouteRecordInfo<
      '/posts/ffmpeg-rtsp-on-m2',
      '/posts/ffmpeg-rtsp-on-m2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Github_Crawler': RouteRecordInfo<
      '/posts/Github_Crawler',
      '/posts/Github_Crawler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/github-learn-cuda': RouteRecordInfo<
      '/posts/github-learn-cuda',
      '/posts/github-learn-cuda',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gitmoji': RouteRecordInfo<
      '/posts/gitmoji',
      '/posts/gitmoji',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/halcon-cplusplus-to-so': RouteRecordInfo<
      '/posts/halcon-cplusplus-to-so',
      '/posts/halcon-cplusplus-to-so',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/halcon-hdict2voc': RouteRecordInfo<
      '/posts/halcon-hdict2voc',
      '/posts/halcon-hdict2voc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/halcon-hwindowcontrol-zoom': RouteRecordInfo<
      '/posts/halcon-hwindowcontrol-zoom',
      '/posts/halcon-hwindowcontrol-zoom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/halcon-used-with-docker': RouteRecordInfo<
      '/posts/halcon-used-with-docker',
      '/posts/halcon-used-with-docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/k8s-install-kubesphere-on-centos7': RouteRecordInfo<
      '/posts/k8s-install-kubesphere-on-centos7',
      '/posts/k8s-install-kubesphere-on-centos7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/move-hexo-to-server': RouteRecordInfo<
      '/posts/move-hexo-to-server',
      '/posts/move-hexo-to-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/paddle-compose-a-word-recognizer': RouteRecordInfo<
      '/posts/paddle-compose-a-word-recognizer',
      '/posts/paddle-compose-a-word-recognizer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python_coroutine': RouteRecordInfo<
      '/posts/python_coroutine',
      '/posts/python_coroutine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python_pyinstaller': RouteRecordInfo<
      '/posts/python_pyinstaller',
      '/posts/python_pyinstaller',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python_PyQt5': RouteRecordInfo<
      '/posts/python_PyQt5',
      '/posts/python_PyQt5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rk3588-devfreq-cpufreq-guide': RouteRecordInfo<
      '/posts/rk3588-devfreq-cpufreq-guide',
      '/posts/rk3588-devfreq-cpufreq-guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/scrapy-crawler-record': RouteRecordInfo<
      '/posts/scrapy-crawler-record',
      '/posts/scrapy-crawler-record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/synology-cloudflare-ddns-ipv6': RouteRecordInfo<
      '/posts/synology-cloudflare-ddns-ipv6',
      '/posts/synology-cloudflare-ddns-ipv6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/synology-frp-with-https': RouteRecordInfo<
      '/posts/synology-frp-with-https',
      '/posts/synology-frp-with-https',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/synology-Intranet-penetration-with-frp': RouteRecordInfo<
      '/posts/synology-Intranet-penetration-with-frp',
      '/posts/synology-Intranet-penetration-with-frp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/synology-ipv6-ddns': RouteRecordInfo<
      '/posts/synology-ipv6-ddns',
      '/posts/synology-ipv6-ddns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tech-texture-and-glcm': RouteRecordInfo<
      '/posts/tech-texture-and-glcm',
      '/posts/tech-texture-and-glcm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tensorrt-tutorial': RouteRecordInfo<
      '/posts/tensorrt-tutorial',
      '/posts/tensorrt-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valine-issue-340': RouteRecordInfo<
      '/posts/valine-issue-340',
      '/posts/valine-issue-340',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wallpaper_shared': RouteRecordInfo<
      '/posts/wallpaper_shared',
      '/posts/wallpaper_shared',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.0-beta.6_vue@3.5.30_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.0-beta.6_@babel+parser@7.29.2_@nuxt+kit@3.21.2_@types+markdown-it@14.1.2_@t_87a0a860dba2bbaf9e7ccd4e422216a5/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.0-beta.6_vue@3.5.30_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.0-beta.6_vue@3.5.30_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/about-my-job.md': {
      routes:
        | '/posts/about-my-job'
      views:
        | never
    }
    'pages/posts/albums_creater.md': {
      routes:
        | '/posts/albums_creater'
      views:
        | never
    }
    'pages/posts/Arknights_extract.md': {
      routes:
        | '/posts/Arknights_extract'
      views:
        | never
    }
    'pages/posts/build-env-for-rasa.md': {
      routes:
        | '/posts/build-env-for-rasa'
      views:
        | never
    }
    'pages/posts/build-shadowsocks.md': {
      routes:
        | '/posts/build-shadowsocks'
      views:
        | never
    }
    'pages/posts/cpp-libwebsockets-server-example.md': {
      routes:
        | '/posts/cpp-libwebsockets-server-example'
      views:
        | never
    }
    'pages/posts/cpp-opencv-mat.md': {
      routes:
        | '/posts/cpp-opencv-mat'
      views:
        | never
    }
    'pages/posts/cpp-std-sort.md': {
      routes:
        | '/posts/cpp-std-sort'
      views:
        | never
    }
    'pages/posts/cross-compile-boost.md': {
      routes:
        | '/posts/cross-compile-boost'
      views:
        | never
    }
    'pages/posts/cross-compile-fmt.md': {
      routes:
        | '/posts/cross-compile-fmt'
      views:
        | never
    }
    'pages/posts/cross-compile-numcpp.md': {
      routes:
        | '/posts/cross-compile-numcpp'
      views:
        | never
    }
    'pages/posts/cross-compile-opencv.md': {
      routes:
        | '/posts/cross-compile-opencv'
      views:
        | never
    }
    'pages/posts/cross-compile-qt5.md': {
      routes:
        | '/posts/cross-compile-qt5'
      views:
        | never
    }
    'pages/posts/cross-compile-spdlog.md': {
      routes:
        | '/posts/cross-compile-spdlog'
      views:
        | never
    }
    'pages/posts/cross-compile-tutorial.md': {
      routes:
        | '/posts/cross-compile-tutorial'
      views:
        | never
    }
    'pages/posts/cross-compile-x264.md': {
      routes:
        | '/posts/cross-compile-x264'
      views:
        | never
    }
    'pages/posts/CSharp-sort-files-with-name.md': {
      routes:
        | '/posts/CSharp-sort-files-with-name'
      views:
        | never
    }
    'pages/posts/cuda-vector-allocator.md': {
      routes:
        | '/posts/cuda-vector-allocator'
      views:
        | never
    }
    'pages/posts/daily-record-1.md': {
      routes:
        | '/posts/daily-record-1'
      views:
        | never
    }
    'pages/posts/daily-record-3.md': {
      routes:
        | '/posts/daily-record-3'
      views:
        | never
    }
    'pages/posts/daily-record-4.md': {
      routes:
        | '/posts/daily-record-4'
      views:
        | never
    }
    'pages/posts/docker-on-wsl2.md': {
      routes:
        | '/posts/docker-on-wsl2'
      views:
        | never
    }
    'pages/posts/ffmpeg-rtsp-on-m2.md': {
      routes:
        | '/posts/ffmpeg-rtsp-on-m2'
      views:
        | never
    }
    'pages/posts/Github_Crawler.md': {
      routes:
        | '/posts/Github_Crawler'
      views:
        | never
    }
    'pages/posts/github-learn-cuda.md': {
      routes:
        | '/posts/github-learn-cuda'
      views:
        | never
    }
    'pages/posts/gitmoji.md': {
      routes:
        | '/posts/gitmoji'
      views:
        | never
    }
    'pages/posts/halcon-cplusplus-to-so.md': {
      routes:
        | '/posts/halcon-cplusplus-to-so'
      views:
        | never
    }
    'pages/posts/halcon-hdict2voc.md': {
      routes:
        | '/posts/halcon-hdict2voc'
      views:
        | never
    }
    'pages/posts/halcon-hwindowcontrol-zoom.md': {
      routes:
        | '/posts/halcon-hwindowcontrol-zoom'
      views:
        | never
    }
    'pages/posts/halcon-used-with-docker.md': {
      routes:
        | '/posts/halcon-used-with-docker'
      views:
        | never
    }
    'pages/posts/k8s-install-kubesphere-on-centos7.md': {
      routes:
        | '/posts/k8s-install-kubesphere-on-centos7'
      views:
        | never
    }
    'pages/posts/move-hexo-to-server.md': {
      routes:
        | '/posts/move-hexo-to-server'
      views:
        | never
    }
    'pages/posts/paddle-compose-a-word-recognizer.md': {
      routes:
        | '/posts/paddle-compose-a-word-recognizer'
      views:
        | never
    }
    'pages/posts/python_coroutine.md': {
      routes:
        | '/posts/python_coroutine'
      views:
        | never
    }
    'pages/posts/python_pyinstaller.md': {
      routes:
        | '/posts/python_pyinstaller'
      views:
        | never
    }
    'pages/posts/python_PyQt5.md': {
      routes:
        | '/posts/python_PyQt5'
      views:
        | never
    }
    'pages/posts/rk3588-devfreq-cpufreq-guide.md': {
      routes:
        | '/posts/rk3588-devfreq-cpufreq-guide'
      views:
        | never
    }
    'pages/posts/scrapy-crawler-record.md': {
      routes:
        | '/posts/scrapy-crawler-record'
      views:
        | never
    }
    'pages/posts/synology-cloudflare-ddns-ipv6.md': {
      routes:
        | '/posts/synology-cloudflare-ddns-ipv6'
      views:
        | never
    }
    'pages/posts/synology-frp-with-https.md': {
      routes:
        | '/posts/synology-frp-with-https'
      views:
        | never
    }
    'pages/posts/synology-Intranet-penetration-with-frp.md': {
      routes:
        | '/posts/synology-Intranet-penetration-with-frp'
      views:
        | never
    }
    'pages/posts/synology-ipv6-ddns.md': {
      routes:
        | '/posts/synology-ipv6-ddns'
      views:
        | never
    }
    'pages/posts/tech-texture-and-glcm.md': {
      routes:
        | '/posts/tech-texture-and-glcm'
      views:
        | never
    }
    'pages/posts/tensorrt-tutorial.md': {
      routes:
        | '/posts/tensorrt-tutorial'
      views:
        | never
    }
    'pages/posts/valine-issue-340.md': {
      routes:
        | '/posts/valine-issue-340'
      views:
        | never
    }
    'pages/posts/wallpaper_shared.md': {
      routes:
        | '/posts/wallpaper_shared'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
