/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/about-my-job': RouteRecordInfo<'/posts/about-my-job', '/posts/about-my-job', Record<never, never>, Record<never, never>>,
    '/posts/albums_creater': RouteRecordInfo<'/posts/albums_creater', '/posts/albums_creater', Record<never, never>, Record<never, never>>,
    '/posts/Arknights_extract': RouteRecordInfo<'/posts/Arknights_extract', '/posts/Arknights_extract', Record<never, never>, Record<never, never>>,
    '/posts/build-env-for-rasa': RouteRecordInfo<'/posts/build-env-for-rasa', '/posts/build-env-for-rasa', Record<never, never>, Record<never, never>>,
    '/posts/build-shadowsocks': RouteRecordInfo<'/posts/build-shadowsocks', '/posts/build-shadowsocks', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-boost': RouteRecordInfo<'/posts/cross-compile-boost', '/posts/cross-compile-boost', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-fmt': RouteRecordInfo<'/posts/cross-compile-fmt', '/posts/cross-compile-fmt', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-numcpp': RouteRecordInfo<'/posts/cross-compile-numcpp', '/posts/cross-compile-numcpp', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-opencv': RouteRecordInfo<'/posts/cross-compile-opencv', '/posts/cross-compile-opencv', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-qt5': RouteRecordInfo<'/posts/cross-compile-qt5', '/posts/cross-compile-qt5', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-spdlog': RouteRecordInfo<'/posts/cross-compile-spdlog', '/posts/cross-compile-spdlog', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-tutorial': RouteRecordInfo<'/posts/cross-compile-tutorial', '/posts/cross-compile-tutorial', Record<never, never>, Record<never, never>>,
    '/posts/cross-compile-x264': RouteRecordInfo<'/posts/cross-compile-x264', '/posts/cross-compile-x264', Record<never, never>, Record<never, never>>,
    '/posts/CSharp-sort-files-with-name': RouteRecordInfo<'/posts/CSharp-sort-files-with-name', '/posts/CSharp-sort-files-with-name', Record<never, never>, Record<never, never>>,
    '/posts/daily-record-1': RouteRecordInfo<'/posts/daily-record-1', '/posts/daily-record-1', Record<never, never>, Record<never, never>>,
    '/posts/daily-record-3': RouteRecordInfo<'/posts/daily-record-3', '/posts/daily-record-3', Record<never, never>, Record<never, never>>,
    '/posts/daily-record-4': RouteRecordInfo<'/posts/daily-record-4', '/posts/daily-record-4', Record<never, never>, Record<never, never>>,
    '/posts/docker-on-wsl2': RouteRecordInfo<'/posts/docker-on-wsl2', '/posts/docker-on-wsl2', Record<never, never>, Record<never, never>>,
    '/posts/ffmpeg-rtsp-on-m2': RouteRecordInfo<'/posts/ffmpeg-rtsp-on-m2', '/posts/ffmpeg-rtsp-on-m2', Record<never, never>, Record<never, never>>,
    '/posts/Github_Crawler': RouteRecordInfo<'/posts/Github_Crawler', '/posts/Github_Crawler', Record<never, never>, Record<never, never>>,
    '/posts/gitmoji': RouteRecordInfo<'/posts/gitmoji', '/posts/gitmoji', Record<never, never>, Record<never, never>>,
    '/posts/halcon-cplusplus-to-so': RouteRecordInfo<'/posts/halcon-cplusplus-to-so', '/posts/halcon-cplusplus-to-so', Record<never, never>, Record<never, never>>,
    '/posts/halcon-hdict2voc': RouteRecordInfo<'/posts/halcon-hdict2voc', '/posts/halcon-hdict2voc', Record<never, never>, Record<never, never>>,
    '/posts/halcon-hwindowcontrol-zoom': RouteRecordInfo<'/posts/halcon-hwindowcontrol-zoom', '/posts/halcon-hwindowcontrol-zoom', Record<never, never>, Record<never, never>>,
    '/posts/halcon-used-with-docker': RouteRecordInfo<'/posts/halcon-used-with-docker', '/posts/halcon-used-with-docker', Record<never, never>, Record<never, never>>,
    '/posts/k8s-install-kubesphere-on-centos7': RouteRecordInfo<'/posts/k8s-install-kubesphere-on-centos7', '/posts/k8s-install-kubesphere-on-centos7', Record<never, never>, Record<never, never>>,
    '/posts/move-hexo-to-server': RouteRecordInfo<'/posts/move-hexo-to-server', '/posts/move-hexo-to-server', Record<never, never>, Record<never, never>>,
    '/posts/od-build-env-on-m2': RouteRecordInfo<'/posts/od-build-env-on-m2', '/posts/od-build-env-on-m2', Record<never, never>, Record<never, never>>,
    '/posts/paddle-compose-a-word-recognizer': RouteRecordInfo<'/posts/paddle-compose-a-word-recognizer', '/posts/paddle-compose-a-word-recognizer', Record<never, never>, Record<never, never>>,
    '/posts/python_coroutine': RouteRecordInfo<'/posts/python_coroutine', '/posts/python_coroutine', Record<never, never>, Record<never, never>>,
    '/posts/python_pyinstaller': RouteRecordInfo<'/posts/python_pyinstaller', '/posts/python_pyinstaller', Record<never, never>, Record<never, never>>,
    '/posts/python_PyQt5': RouteRecordInfo<'/posts/python_PyQt5', '/posts/python_PyQt5', Record<never, never>, Record<never, never>>,
    '/posts/scrapy-crawler-record': RouteRecordInfo<'/posts/scrapy-crawler-record', '/posts/scrapy-crawler-record', Record<never, never>, Record<never, never>>,
    '/posts/synology-cloudflare-ddns-ipv6': RouteRecordInfo<'/posts/synology-cloudflare-ddns-ipv6', '/posts/synology-cloudflare-ddns-ipv6', Record<never, never>, Record<never, never>>,
    '/posts/synology-frp-with-https': RouteRecordInfo<'/posts/synology-frp-with-https', '/posts/synology-frp-with-https', Record<never, never>, Record<never, never>>,
    '/posts/synology-Intranet-penetration-with-frp': RouteRecordInfo<'/posts/synology-Intranet-penetration-with-frp', '/posts/synology-Intranet-penetration-with-frp', Record<never, never>, Record<never, never>>,
    '/posts/synology-ipv6-ddns': RouteRecordInfo<'/posts/synology-ipv6-ddns', '/posts/synology-ipv6-ddns', Record<never, never>, Record<never, never>>,
    '/posts/valine-issue-340': RouteRecordInfo<'/posts/valine-issue-340', '/posts/valine-issue-340', Record<never, never>, Record<never, never>>,
    '/posts/wallpaper_shared': RouteRecordInfo<'/posts/wallpaper_shared', '/posts/wallpaper_shared', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
